### ISSUE TITLE
Introduce generic domains

### ISSUE THREAD

**Issue by fu-sen** [domcloud/domcloud-id#2]
You currently offer all of the services in Indonesian ccTLD `.id`.
This has a negative effect on search results outside Indonesia. 
This is one of the reasons your service is unknown and ignored.

You should deploy your English site in generic domains other than ccTLDs.
Although `domcloud.com` and` domcloud.net` are registered, there are many other options now.

- domcloud.dev (https only)
- domcloud.site
- domcloud.app (https only)
- domcloud.network
- domcloud.asia (Google treats it like a gTLD)
- domcloud.host

You still have a choice. Please do not operate the English site with `.id` anyway.

**Comment by willnode** [comment]
I was thinking about the same. However there's many things to consider as part of the internationalization effort:

+ Introducing paypal option
+ Introducing another free domain, non .id option (also new location server)
+ Partnering with other domain registrar (because current seller requires you to input national ID number)
 
DOM Cloud has just grown up since last 2020 so it takes time to match the budget and demand.

**Comment by fu-sen** [comment]
I agree. You should do it wherever you can.
It's also ideal for people in the Asia region and Australia, even if it's not, and could be used for web builds and deployments, or on the back end. I feel the potential for success in the service.

PayPal is ideal for payment. If possible or credit card (VISA or Master)

I haven't seen a paid plan in the current situation, but can I set up a domain bring-in? I'm Japanese so I can use the `.jp` domain, but that would be difficult for you to provide.

**Comment by willnode** [comment]
I just registered https://domcloud.io/ . Kinda expensive but I feel it's worthy. I will close this issue once the new site is ready. I will set-up everything else also in near time.

Thank you for your feedback.

**Comment by fu-sen** [comment]
I feel that the domain of your choice is a developer's point of view.
You also like GitHub Pages and look closely at Google's behavior:
https://developers.google.com/search/docs/advanced/crawling/managing-multi-regional-sites#generic-domains

I'm using DOM Cloud with a free plan, but it would be nice to comment here for any new information you've applied.
Therefore, leave it open here as it is.

**Comment by fu-sen** [comment]
Good job! 👍
I can see the English site displayed by `domcloud.io` and the addition of the New York server.
You may do a little more work, but I'm closing this because I'm getting enough attention for this issue. from now on
I look forward to the success of.
