### ISSUE TITLE
Registered in firehol / blocklist

### ISSUE THREAD

**Issue by fu-sen** [domcloud/domcloud-id#4]
From a recent report, I searched the blacklist. Unfortunately the Singapore server is registered:
https://github.com/firehol/blocklist-ipsets/search?q=68.183.191.223

There may still be malicious things on the server.

No New York server was registered here
https://github.com/firehol/blocklist-ipsets/search?q=104.236.24.119

So please note that I put it in the `domcloud-id` issue.

**Comment by fu-sen** [comment]
To put it a little further, other web services are also under attack in a similar way. The web service is still on this list.

**Comment by willnode** [comment]
Thanks for this notice, I'll address it soon.

**Comment by willnode** [comment]
This is a follow up, according to https://www.abuseipdb.com/check/68.183.191.223 the attack still persist so it must come from compromised website in premium hosts, I decided to put all users in a firewall now.

**Comment by fu-sen** [comment]
Looking at the reports on this link, it looks like an older version of WordPress is being attacked. The content will be on the Singapore server.

**Comment by willnode** [comment]
The singapore server no longer contains abuse reports for about a week. It's safe for now on.

**Comment by piglinpotatoes** [comment]
68.183.191.223 is listed on AbuseIPDB and Spamhaus XBL:
* https://www.abuseipdb.com/check/68.183.191.223
* https://check.spamhaus.org/listed/?searchterm=68.183.191.223

**Comment by willnode** [comment]
Thank you for reporting. I have resolved this issue about 12 hours ago and it seems no additional report found. We'll clean the report by the next week.
