### ISSUE TITLE
New host generation is wrong (Singapore server only)

### ISSUE THREAD

**Issue by fu-sen** [domcloud/domcloud-id#5]
I'm trying to host a new Singapore server, but it spawns several times and it all fails.

When I look at the **deploy**, I see the following line.
```
CRITICAL: SSH login failed. Most procedure will not execute.
```
The generated website is returning `ERR_TOO_MANY_REDIRECTS`.

In line with this, the portal response is currently significantly worse. I sometimes see the `502 Bad Gateway`.
I feel that something is obviously wrong.
Even in this state, the New York server successfully created a new host. Therefore, I am reporting to `domcloud-id`.

**Comment by willnode** [comment]
I forgot to turn the swapfile on. It should back to normal now.

**Comment by fu-sen** [comment]
Yes, the response is obviously faster. When I looked at the system status, swap was 0B.
![スクリーンショット 2021-06-27 08 07 31](https://user-images.githubusercontent.com/5434159/123527987-eb345c00-d71e-11eb-9887-14b67dca0440.jpg)

I will try to work on the portal again.

**Comment by willnode** [comment]
Yeah, it's a common mistake. Now I have put this under cron job bootup so I won't need to turn it back on manually again.

**Comment by fu-sen** [comment]
No, it was too fast to close the issue. The portal response is lighter, but creating a new host is still problematic. There still seems to be some other problem.

**Comment by fu-sen** [comment]
The New York server can successfully generate a new host, but there is a problem with subsequent template generation.
The issue is related to `dom-portal`, but you are aware of it so let's continue with this issue.

**Comment by willnode** [comment]
I noticed that in some cases invoking webmin host creation took longer than 30 seconds, which is the maximum time NginX can process. I will try to put it as a background job instead.

**Comment by fu-sen** [comment]
I have confirmed that the New York server `*.domcloud.io` works perfectly, including the template behavior.
On the other hand, the Singapore server `*.dom.my.id` cannot be newly used even now because the host creation is abnormal.
Something is wrong with the Singapore server.

**Comment by willnode** [comment]
I checked your log files, it turns out the sga server actually correct. You [missed](https://github.com/domcloud/domcloud-io/issues/10#issuecomment-869021013) the `fastcgi: off` and `firewall: off` hence the firewall kicks in. The firewall isn't gone, just need to be disabled explicitly. 

You just need to put those to your existing template. No need to separate the template because the deployer knows the execution order automatically.

Btw, the nyc server had problem with it's iptables config. Turns out iptables config is far less reliable than nginx one. It gone back now.

**Comment by fu-sen** [comment]
I am trying 2 different steps at this time.
-  Template containing `root: public_html/site`: This should turn off the firewall.
- Default template: I created a new host regardless of the template.

So what I'm talking about right now is a problem that's occurring independently of the template.

**Comment by willnode** [comment]
No, just setting the root to a subfolder doesn't turn it off, neither `fastcgi: off`. Explicitly telling `firewall: off` will do.

And by default firewall record will be added after creation of new host,

**Comment by fu-sen** [comment]
Hmm? You seem to be looking only at the effects of firewalls. See the original text where I put this issue. I'm not talking about firewalls: https://github.com/domcloud/domcloud-id/issues/5#issue-930808868

**Comment by fu-sen** [comment]
I created a Singapore server with the default template. You will know the host name. Please understand what is happening again.

**Comment by willnode** [comment]
Ok I know the root problem. There's rogue username exist with that same name and that's prevent the creation of new host. Deleted it now.

**Comment by willnode** [comment]
Anyway, feel free to drop an email to me if you need to solve problems privately.

**Comment by fu-sen** [comment]
Oh awesome! Our DOM Cloud is back.

I revived the GitHub project during this time. I needed that template. I also added a setting to disable the firewall:
- https://github.com/fu-sen/DOMCloud-MkDocs
- https://github.com/fu-sen/zerossl.domcloud.io

https://mkdocs.dom.my.id/ wouldn't have been created by anyone other than me. It seems half-baked by creating or deleting.
Probably the timing when the load on the server was high.

It's time to close the issue. After that, we need to be careful about malicious attacks again. 
Thank you for your support so far.

p.s. I'm looking at my profile, has PayPal payment been enabled?

**Comment by willnode** [comment]
Glad it worked now.

PayPal is enabled, though nobody has tested to pay with it so far.

**Comment by fu-sen** [comment]
> PayPal is enabled, though nobody has tested to pay with it so far.

https://domcloud.io/price

FAQ `What are the payment methods?` Has not been updated.
I can work with PayPal, so I might be the first one. I am thinking about that possibility.
